version: '3.1'

services:

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      # This are temporary credentials, i need to figure out how to allow users
      # to set their own credentials when usig this headless CMS
      MONGO_INITDB_ROOT_USERNAME: looped
      MONGO_INITDB_ROOT_PASSWORD: root

  api:
    build:
      context: .
      dockerfile: .docker/api.dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNSTRING=mongodb://looped:root@db
