# Mail
# Mail configurations to allow emails to go out
MAIL_PORT: 587
MAIL_HOST: smtp.gmail.com
MAIL_PASSWORD: password
MAIL_USERNAME: example@gmail.com

# DB
# MongoDB Connection String - for more info, visit
# https://www.mongodb.com/docs/manual/reference/connection-string/
MONGODB_CONNSTRING: mongodb://localhost:27017
