name: API

on:
  push:
    branches: [ main ]
    paths:
      - "**.go"
      - ".github/workflows/api.yml"

  pull_request:
    branches: [ main ]
    paths:
      - "**.go"
      - ".github/workflows/api.yml"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Set up Docker"
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: "latest"
        # Optional: golangci-lint command line arguments.
        args: -v


    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: install packages
      run: go get ./...

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
